2022-07-06 18:44:59,699 INFO    Thread-24 :29262 [wandb_setup.py:_flush():76] Configure stats pid to 29262
2022-07-06 18:44:59,699 INFO    Thread-24 :29262 [wandb_setup.py:_flush():76] Loading settings from /home/b65580/.config/wandb/settings
2022-07-06 18:44:59,699 INFO    Thread-24 :29262 [wandb_setup.py:_flush():76] Loading settings from wandb/settings
2022-07-06 18:44:59,699 INFO    Thread-24 :29262 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'uncategorized', 'entity': 'panas', 'root_dir': '/home/b65580/Documents/clasificador_de_sentimientos/Prototypes', 'run_id': 'ofcpt2oh', 'sweep_param_path': '/home/b65580/Documents/clasificador_de_sentimientos/Prototypes/wandb/sweep-xbc7jvyw/config-ofcpt2oh.yaml', 'sweep_id': 'xbc7jvyw'}
2022-07-06 18:44:59,699 INFO    Thread-24 :29262 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-07-06 18:44:59,699 INFO    Thread-24 :29262 [wandb_init.py:_log_setup():461] Logging user logs to /home/b65580/Documents/clasificador_de_sentimientos/Prototypes/wandb/run-20220706_184459-ofcpt2oh/logs/debug.log
2022-07-06 18:44:59,699 INFO    Thread-24 :29262 [wandb_init.py:_log_setup():462] Logging internal logs to /home/b65580/Documents/clasificador_de_sentimientos/Prototypes/wandb/run-20220706_184459-ofcpt2oh/logs/debug-internal.log
2022-07-06 18:44:59,699 INFO    Thread-24 :29262 [wandb_init.py:_jupyter_setup():411] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fd850935040>
2022-07-06 18:44:59,700 INFO    Thread-24 :29262 [wandb_init.py:init():495] calling init triggers
2022-07-06 18:44:59,700 INFO    Thread-24 :29262 [wandb_init.py:init():498] wandb.init called with sweep_config: {'model': 'Tree', 'n_estimators': 900}
config: {}
2022-07-06 18:44:59,700 INFO    Thread-24 :29262 [wandb_init.py:init():548] starting backend
2022-07-06 18:44:59,700 INFO    Thread-24 :29262 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-07-06 18:44:59,706 INFO    Thread-24 :29262 [backend.py:ensure_launched():217] starting backend process...
2022-07-06 18:44:59,713 INFO    Thread-24 :29262 [backend.py:ensure_launched():222] started backend process with pid: 29605
2022-07-06 18:44:59,715 INFO    Thread-24 :29262 [wandb_init.py:init():558] backend started and connected
2022-07-06 18:44:59,721 INFO    Thread-24 :29262 [wandb_run.py:_config_callback():1131] config_cb None None {'model': 'Tree', 'n_estimators': 900}
2022-07-06 18:44:59,724 INFO    Thread-24 :29262 [wandb_run.py:_label_probe_notebook():1084] probe notebook
2022-07-06 18:44:59,724 INFO    Thread-24 :29262 [wandb_run.py:_label_probe_notebook():1094] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-07-06 18:44:59,724 INFO    Thread-24 :29262 [wandb_init.py:init():634] updated telemetry
2022-07-06 18:44:59,746 INFO    Thread-24 :29262 [wandb_init.py:init():665] communicating run to backend with 30 second timeout
2022-07-06 18:45:01,733 INFO    Thread-24 :29262 [wandb_run.py:_on_init():1919] communicating current version
2022-07-06 18:45:02,343 INFO    Thread-24 :29262 [wandb_run.py:_on_init():1923] got version response 
2022-07-06 18:45:02,343 INFO    Thread-24 :29262 [wandb_init.py:init():700] starting run threads in backend
2022-07-06 18:45:02,414 INFO    Thread-24 :29262 [wandb_run.py:_console_start():1893] atexit reg
2022-07-06 18:45:02,415 INFO    Thread-24 :29262 [wandb_run.py:_redirect():1766] redirect: SettingsConsole.WRAP
2022-07-06 18:45:02,415 INFO    Thread-24 :29262 [wandb_run.py:_redirect():1803] Wrapping output streams.
2022-07-06 18:45:02,416 INFO    Thread-24 :29262 [wandb_run.py:_redirect():1827] Redirects installed.
2022-07-06 18:45:02,416 INFO    Thread-24 :29262 [wandb_init.py:init():732] run started, returning control to user process
2022-07-06 18:45:02,416 INFO    Thread-24 :29262 [wandb_run.py:_finish():1680] finishing run panas/uncategorized/ofcpt2oh
2022-07-06 18:45:02,417 ERROR   Thread-24 :29262 [jupyter.py:save_history():427] Run pip install nbformat to save notebook history
2022-07-06 18:45:02,417 INFO    Thread-24 :29262 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2022-07-06 18:45:02,417 INFO    Thread-24 :29262 [wandb_init.py:_jupyter_teardown():393] cleaning up jupyter logic
2022-07-06 18:45:02,417 INFO    Thread-24 :29262 [wandb_run.py:_atexit_cleanup():1862] got exitcode: 1
2022-07-06 18:45:02,420 INFO    Thread-24 :29262 [wandb_run.py:_restore():1834] restore
2022-07-06 18:45:03,254 INFO    Thread-24 :29262 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  total_bytes: 815
}

2022-07-06 18:45:03,357 INFO    Thread-24 :29262 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  total_bytes: 815
}

2022-07-06 18:45:04,240 INFO    Thread-24 :29262 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 815
  total_bytes: 815
}

2022-07-06 18:45:04,752 INFO    Thread-24 :29262 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 815
  total_bytes: 2447
}

2022-07-06 18:45:04,855 INFO    Thread-24 :29262 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 815
  total_bytes: 2447
}

2022-07-06 18:45:04,957 INFO    Thread-24 :29262 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 815
  total_bytes: 2447
}

2022-07-06 18:45:05,060 INFO    Thread-24 :29262 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 815
  total_bytes: 2447
}

2022-07-06 18:45:05,160 INFO    Thread-24 :29262 [wandb_run.py:_restore():1834] restore
2022-07-06 18:45:07,607 ERROR   Thread-24 :29262 [wandb_run.py:_atexit_cleanup():1883] Problem finishing run
Traceback (most recent call last):
  File "/tmp/ipykernel_29262/2226497219.py", line 17, in train
    for epoch in range(config["epochs"]):
  File "/home/b65580/Documents/clasificador_de_sentimientos/Prototypes/proto_env/lib/python3.8/site-packages/wandb/sdk/wandb_config.py", line 128, in __getitem__
    return self._items[key]
KeyError: 'epochs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/b65580/Documents/clasificador_de_sentimientos/Prototypes/proto_env/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1871, in _atexit_cleanup
    self._on_finish()
  File "/home/b65580/Documents/clasificador_de_sentimientos/Prototypes/proto_env/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1996, in _on_finish
    time.sleep(0.1)
Exception
